name: rick_and_morty_jose_jet
description: Prueba técnica de Jose Esteve para AllInBicking. SDK
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.0.3
  effective_dart: ^1.3.1
  mocktail: ^0.3.0
  test: ^1.17.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
